### ISSUE TITLE
Code Annotations: Todd Estes

### ISSUE THREAD

**Issue by Todd-Estes** [mdflynn/Crate#36]
5 Feb - Work in Progress

This should cover the changes to the User model in order to satisfy the new requirements for the User Show (info) page, following the new User attributes (image, description, shipping address) column migrations:

modules/user/model.js Add new attributes (image, description, shipping address) to User model

modules/user/types.js Add new attributes (image, description, shipping address) to User type fields

modules/user/mutatuons.js Add new update mutation to User type

modules/user/resolvers.js Add new update method/resolver to User type

modules/user/types.js Add new User model attributes to User type

?? - modules/user/query.js Add new attributes to getById query for User Show page ?? Unsure about this

This is what I was thinking so far as to the addition of the "Order" model migration. As yet, I have not added any annotations in regard to the new joins tables that will most likely be needed:

setup/schema/models.js Add Order model

setup/schema/mutatuons.js Add Order model to object type fields

setup/schema/queries.js Import Order model and add Oder to query fields

**Comment by helloeduardo** [comment]
Closing for backlog grooming. Thanks for your annotations! Don't forget to submit a link to your branch if you haven't already [here](https://forms.gle/oZFYLVDWFzMN8v3e6)
